### ISSUE TITLE
SSH error

### ISSUE THREAD

**Issue by laurencefass** [philm/ansible_playbook#8]
im trying to use this for the first time. with a simple playbook. im not getting a sensible output and I would be very grateful for any advice you can offer.

here is my playbook.yml

```
---
- hosts: ansible_target
  tasks:
      - name: Create file hello
        file:
            path: /tmp/hallo
            state: touch

      - name: Create file world
        file:
            path: /tmp/world
            state: touch
```

im running the target, followed by the playbook container.

target:
`
docker run -d -p 2222:22 --name ansible_target -v ~/.ssh/id_rsa.pub:/home/ubuntu/.ssh/authorized_keys philm/ansible_target`

playbook

`docker run --link ansible_target --rm -it -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub -v $(pwd):/ansible/playbooks philm/ansible_playbook -v playbook.yml`

output:
```
PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
fatal: [ansible_target]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *********************************************************************
ansible_target             : ok=0    changed=0    unreachable=1    failed=0
```

any advice much appreciated

many thanks
